AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Maps Runner Lambda

Resources:
  MapsRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: maps-runner
      Handler: maps-runner.lambda_handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 128
      Timeout: 300
      Layers:
        - arn:aws:lambda:eu-west-1:924947995844:layer:pyodbc-layer:4
      Policies:
        - AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::924947995844:role/AcmePreviewEnvironmentEC2
      Events:
        FiveMinuteTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  MapsRunnerFunction:
    Description: "Maps Runner Lambda ARN"
    Value: !GetAtt MapsRunnerFunction.Arn
