name: Preview Environment Pipeline

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Customer name'
        required: true
        type: string
      mapsunified_pr:
        description: 'Mapsunified PR'
        required: false
        type: string
      mapsdatabase_pr:
        description: 'Mapsdatabase PR'
        required: false
        type: string

jobs:
  publish-to-maps-database:
    if: ${{ github.event.inputs.mapsdatabase_pr != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and restore DB
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Downloading backup file..."
            aws s3 cp s3://acme-preview-database-backups/PreviewEnvironmentDB.bak /var/opt/mssql/data/PreviewEnvironmentDB.bak

            echo "SQL Server starting the restore..."
            /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '${{ secrets.DB_SA_PASSWORD }}' -Q "RESTORE DATABASE [PreviewEnvironmentDB] FROM DISK = '/var/opt/mssql/data/PreviewEnvironmentDB.bak' WITH REPLACE"

  build-image-and-push:
    if: ${{ github.event.inputs.mapsunified_pr != '' }}
    runs-on: ubuntu-latest
    env:
      VERSION: 0.${{ github.run_number }}
      AWS_REGISTRY: ${{ '924947995844.dkr.ecr.eu-west-1.amazonaws.com/mapsunified-dev-repository' }}
    steps:
      - name: Checkout specific branch of another repository
        uses: actions/checkout@v3
        with:
          repository: inventanalytics/mapsunified # Replace with the actual owner/repo name
          ref: ${{ github.event.inputs.mapsunified_pr }}       # Specify the branch name here
          path: .   # Directory to clone the other repo into
          token: ${{ secrets.TOKEN }} # Required for private repositories

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image for AWS
        shell: bash
        run: |
          docker build -t $AWS_REGISTRY:$VERSION -t $AWS_REGISTRY:latest .
          echo "Building image..."

      - name: Push Docker Image to AWS ECR
        shell: bash
        run: |
          docker push $AWS_REGISTRY:$VERSION
          docker push $AWS_REGISTRY:latest
          echo "Pushing image..."

  create-and-deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      
      - name: Build SAM application
        run: sam build --template-file maps-runner/template.yml

      - name: Deploy SAM application
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name maps-runner-stack \
            --capabilities CAPABILITY_IAM \
            --s3-bucket acme-preview-lambda-buckets

  invoke-lambda-function:
    runs-on: ubuntu-latest
    needs: create-and-deploy-lambda

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Create payload file
        run: |
          echo '{ "name": "Onur" }' > payload.json
      
      - name: Invoke Lambda Function
        run: |
          aws lambda invoke \
            --function-name Preview-Environment-Hello-World \
            --payload file://payload.json \
            response.json

      - name: Show Lambda response
        run: cat response.json
